version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: porthub-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190946
      POSTGRES_DB: porthub_db
    ports:
      - "5432:5432"
    volumes:
      # เชื่อมไฟล์ SQL สำหรับสร้างตารางครั้งแรก
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # เก็บข้อมูลไว้ใน Volume ไม่ให้หายเมื่อปิด Container
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: