version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: porthub-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190946
      POSTGRES_DB: porthub_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
